apiVersion: v1
kind: Secret
metadata:
  name: smartvault-secrets
type: Opaque
stringData:
  SMARTVAULT_S3_ACCESS_KEY: ""
  SMARTVAULT_S3_SECRET_KEY: ""
  SMARTVAULT_LOCAL_MASTER_KEY_BASE64: ""
  SMARTVAULT_KMS_KEY_ID: ""
